### ISSUE TITLE
Nesting CSS does not work with textual-dev

### ISSUE THREAD

**Issue by mohammad-sayed-ahmad** [Textualize/textual-dev#31]
Hello everyone,
I have been recently using the textual-dev cli and I have been facing an extremely peculiar issue.
Whenever I try nesting CSS using the `&` it fails horibbly.

Minimum Reproducible Example:

**issue.py**
```python
from textual.app import App
from textual.widgets import Static

class BasicWidget(Static):
    def compose(self):
        yield Static("Inside", classes="inside")


class BasicApp(App):
    CSS_PATH = "issue.tcss"
    def compose(self):
        yield BasicWidget()
    

if __name__ == '__main__':
    app = BasicApp()
    app.run()
```
**issue.tcss**
```css
BasicWidget {
    background: red;
    width: 40;

    & .inside {
        background: green;
        width: 10;
    }
}
```
———————————————————————————————————————————————————————————
Commands Tested:
`python issue.py` -> Works normally
`textual run issue.py --dev` -> The following error in stylesheet:

```bash
 • Expected one of 'comment line', 'comment start', 'declaration name', 'declaration set end', or 'whitespace'.
 • Did you forget a semicolon at the end of a line?
```
